### ISSUE TITLE
Running Failed

### ISSUE THREAD

**Issue by jmkitavi** [atticoos/ReactNative-Redux-Todo-List#4]
Hello, I cloned and am trying to the project but I keep running into an error with watchman.
Below is a screenshot of the error.
![image](https://user-images.githubusercontent.com/17447937/32169847-294ca7d6-bd83-11e7-9ff0-34c3b566a7b5.png)
Help will be appreciated.

**Comment by atticoos** [comment]
There's a thread over in https://github.com/facebook/react-native/issues/2941 that appears to cover this. This project does run an early version of React Native, which might have a stricter dependency on watchman.

**Comment by jmkitavi** [comment]
@ajwhite Solved it by using the facebook version of watchman.
Think you can close this.
But quick query, how do you run it on ios

**Comment by atticoos** [comment]
That's great to hear 👍 

You can open the XCode project and hit "run" to launch the app in a simulator or device. Since this project uses an older version of `react-native`, you might be able to get away with `react-native run-ios`, but no guarantees.
